services:     # not allow \t 
  mariadb:
    container_name: mariadb 
    build:   
      context: ./requirements/mariadb  #location the docker file 
    image: mariadb   # name image same the name of the servers 
    env_file:
      - .env   # element we add a .env
    restart: always   # in any failure we must rebuild the image 
    volumes:
      - mariadb_data:/var/lib/mysql  # read write the data to keep the data when we close the continuer 
    networks:
      - inception   # network name   

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    image: wordpress
    env_file:
      - .env
    restart: always
    depends_on:
      - mariadb    # 
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    image: nginx
    env_file:
      - .env
    restart: always
    depends_on:
      - wordpress
    ports:
      - "443:443" #  inter point the browser how connect with it why ? 
    volumes:
      - wordpress_data:/var/www/html # why add a wordpress ?
    networks:
      - inception

volumes: 
  mariadb_data:  # here we save the data 
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/mariadb # user == my intra name    
      o: bind 

  wordpress_data: # here we save the file images  
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/wordpress
      o: bind

networks:   # host network == my network            docker network == not allow to use it 
  inception:
    driver: bridge